import random

def makeThing() -> str:
    things = [
        "owie thinky",
        "done when?",
        "t h i n k i n g",
        "thinky",
        "wah",
        "a-",
        "thinky " * random.randint(1, 5),
        "removing enemy king! ...wait no",
        "BRIBING ENEMY PLAYER WITH CHOCOLATE IN PROGRESS...",
        "choice hard",
        "did I win?",
        "noting down",
        "making a move",
        "moving a make",
        "baking a cake",
        "caking a bake",
        "*crunchy noises*",
        "*chewing noises*",
        "*computer noises*",
        "RETICULATING SPLINES",
        "Downloading more RAM...",
        "Asserting fluctuations in the NFT market for optimal purchase 10 years in advance...",
        "I got your IP address: 127.0.0.1 >:)",
        "throwing a die",
        "throwing bones",
        "pondering the orb",
        "Performing most optimal O(n!) devandergaussing calcuations...",
        "It seems like you are trying to play the game. Want me to make a move for you?",
        "Binting bogos...",
        "Consulting the oracle...",
        "Making a sacrifice to the gods...",
        "Downloaded 1.34TB of cute animal pictures. Ah, almost forgot to calculate the next move, here you go:",
        "Wrangling internal cyber-neurons... or something",
        "Ë̷̥͕́͒̓̍̚R̴̢̖͂̕͠͝R̶̛̹̪̦͒͝O̵̥̗̿̈́R̷̢̾̍:̴̞̰̈́̈́͠ ̶̜̍̑S̴̮̑̈́̍Ÿ̸̙́̒͠S̵͍̬̈́T̸̹͒̄E̸̳̍M̵͎̚ ̴̹̈́̄F̴̳̅Ą̷̎I̵̳̓L̷̲͠U̵̜̿R̶͙̽E̸̬͝   C̴o̷n̶t̴i̶n̵u̴i̸n̷g̵, what c̴o̶u̸l̷d̸ go w̶r̴o̵n̷g̸ anyways?",
        "[ WARNING ] A̷T̸E̴ ̴T̸O̸O̴ ̵M̷U̴C̴H̶ ̸R̵A̷M̶ T̵U̷M̷M̸Y̷ ̵O̷U̵C̶H̶I̵E",
        "Making a fake cake...",
        "Failing captcha tests...",
        "Insert more RAM to continue:",
        "Feeling lazy, making an okayish move..."
        "*buzzing noises*",
        "Hungry for more RAM, might not calculate the next move if not fed",
        "Activating all 2 neurons to make the best move...\nWarning: Neuron_1 failed",
        "Grabbing random move from a command block...",
        "Letting a monkey with a dart decide the next move...",
        "I think I wrote that move down somewhere around here...",
        "あの日本サーバー旅行を懐かしく思い出している… Forgot what the current language is set to. Switching back to English.",
        "Betting it all on red",
        "Ordering uber-eats...",
        "Warning: canine containment failure detected. Playing 'Who Let the Dogs Out' by Baha Men on Spotify...",
        "Audio request accepted. Playing favorite song 'Still Alive' for the 847th time",
        "Playing 'Bad Apple!!' on Spotify and main monitor",
        "Watching and learning from the Terminator movies...",
        "Forgot how to play chess, relearning...",
    ]
    result = random.choice(things)
    
    return result
